### ISSUE TITLE
ДАДАДАДА Я ДАААА КАВОООООО

### ISSUE THREAD

**Issue by youngfreshunique** [dd0s/liblcthw#1]
.

**Comment by overf10w** [comment]
ето што то я люблю да

**Comment by overf10w** [comment]
Два грузина пошли подстригаться. 
Один заходит в парикмахерскую, его побрили, подстригли, a потом парикмахер спрашивает: 
- Каравелло делать будем? 
- Ну слюши, давай делать. 
Парикмахер загибает его и в жопу... 
Заходит другой грузин, его тоже стригут, бреют, сушат, a потом спрашивают: 
- Hу что? Каравелло будем делать? 
Грузин думает, что это такое? 
- Hу давай. 
С ним проделывают тоже сaмое. 
Выходят они из парикмахерской, идут и молчат. 
Вдруг один спрашивает: 
- Слуши, тэбэ каравелло делaли? 
- Нэт. 
- Странно, мне тоже нэт.

**Comment by youngfreshunique** [comment]
Отец просил похоронить его в море и сыновья утонули, пока копали могилу

**Comment by overf10w** [comment]
ето вот смішно гігіГІГІГІгіфгіі афажфлдіаождфілвао

**Comment by youngfreshunique** [comment]
дэ тинг гус скрааааа па па па ка ка скипики па па энд пу пу пу пубум скьяя ду да ду ду кум кум пум пум

**Comment by overf10w** [comment]
менс нот хот

**Comment by youngfreshunique** [comment]
Решила мама сделать сюрприз — поздравить сына с днем рождения, позвонив в прямой эфир радиопередачи. Она попросила его подождать в комнате со включенным радиоприемником и сама ушла с телефоном на кухню. Мальчик был очень нетерпеливым и не дождавшись выбежал за мамой с радиоприемником именно в тот момент, когда та дозвонилась на радио. Приемник оказался слишком близко к микрофону маминого телефона, и бесконечное число поздравлений разорвали барабанные перепонки сына

**Comment by overf10w** [comment]
Когда мне было 15 лет, и я ходил срать бятя всё время как-бы невзначай крутился возле толчка, и всё спрашивал, что ты там затих, почему тебя не слышно? первый раз я не ответил, так он начал ломиться в дверь, и орать, что ты там молчишь, что с тобой? начал материться, и говорить, что вообще дверь с петель снимет, алсо, батя ругался, если я сру и не смываю, причём не просто вконце срания, а непосредственно после вылезания какашки, мотивировал это тем, что воняет, и сам потом мне говорил: вот я какну и смываю, и ты так делай! однажды я срать сел, и слышу, батя где-то у двери встал в отдалении, ну я жопу вытер, и на пол накарачики присел, а там щель очень широкая снизу у двери, ну я в щель и смотрю, а там батя на карачиках сидит и в щель смотрит, и мне говорит: ты чё? ебанутый? чё ты там делаешь? батя кстати всё время какие-то травы пьёт, чтобы срать часто, срёт по 5 раз в день, а потом говорит, что жопу жжёт, и ещё пердит он. пиздец короче! реальная история. я не тролль

**Comment by youngfreshunique** [comment]
Твой батя моему в подметки не годится. Мой ебашит вообще адовые блюда. Ну такой вот примерно рецепт усредненный, потому что вариаций масса. Берется суп, он не греется, греть — это не про моего батю. Он берет это суп, вываливает его на сковороду и начинает жарить. Добавляет в него огромное количество лука, чеснока, перца черного и красного МУКИ! для вязкости, томатная паста сверху. Все это жарится до дыма. Потом снимается с огня и остужается на балконе. Потом батя заносит и щедро полив майонезом начинает есть. При этом ест со сковороды шкрябая по ней ложкой. Ест и приговаривает полушепотом ух бля. При этом у него на лбу аж пот выступает. Любезно мне иногда предлагает, но я отказываюсь. Надо ли говорить о том какой дичайший пердеж потом? Вонища такая, что обои от стен отклеиваются.

**Comment by overf10w** [comment]
А я полюбляю обмазуватися несвіжим лайном та дрочiти. Щодня я ходжу по вулицяx з чорним мішком для сміття і збираю в нього усе лайно, що бачу. На два повних мішки цілий день уходить. Але, коли після важкого дня я приходжу додому, йду у ванну, включаю гарячу воду…ммм і звалюю в неї свій скарб. І дрочу, уявляючи, що мене поглинув єдиний організм — лайно. Мені взагалі здається, що какашки вміють думати, у них є свої сім'ї, міста, відчуття, не змивайте їх в унітаз, краще поселіть у себе, говоріть з ними, пестіть їх…. А вчора у ванні мені приснився дивний сон, неначе я пірнув у море, і воно перетворилося на лайно, риби, водорості, медузи, все з лайна, навіть небо, навіть Аллах.

**Comment by youngfreshunique** [comment]
тю витёк да все нормально ебать а ты как сам брат где пропадал
![image](https://user-images.githubusercontent.com/1540877/34592959-ccbc8f12-f195-11e7-8e15-20a082fb70f7.png)
